openapi: "3.0.2"
info:
  title: MURAL Deprovisioning API
  description: >-
    The Mural's **Provisioning API** is organized around **REST**. 

    The API uses HTTP response codes to indicate API errors. The API supports cross-origin resource sharing. 

    **JSON** is returned by all API responses, including errors.

    Base path: https://app.mural.co/api
  version: 0.0.1
  x-logo:
    url: "https://app.mural.co/static/images/new-logo.svg"
    href: "http://mural.co"
servers:
  - url: https://app.mural.co/api/{version}
    description: The production API server
    variables:
      version:
        default: v0
paths:
  "/v0/provisioning/users/suspend":
    put:
      security:
        - apiKey: []
      tags:
        - Deprovisioning
      summary: Suspend a user account
      description: >-
        Suspend a user account based on the user's email address
      operationId: suspendUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: "string"
                  format: "email"
      responses:
        "200":
          description: Success
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

  "/v0/provisioning/users/unsuspend":
    put:
      security:
        - apiKey: []
      tags:
        - Deprovisioning
      summary: Unsuspend a user account
      description: >-
        Unsuspend a user account based on the user's email address
      operationId: unsuspendUser
      x-code-samples:
        - lang: 'Curl'
          source: |
            "curl -X PUT -H \"authorization: apikey $apiKey\" -H \"Content-Type: application/json\" -d '{\"email\": \"user@example.com\"}' \"https://app.mural.co/api/v0/provisioning/users/unsuspend\""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: "string"
                  format: "email"
      responses:
        "200":
          description: Success
        "401":
          $ref: "#/components/responses/Unauthorized"
        "400":
          $ref: "#/components/responses/BadRequest"
      

components:
  schemas:
    Error:
      description: Details regarding an error response from the API.
      properties:
        error:
          description: "Short, human readable, description of the error"
          example: error message
          type: string
      required:
        - error
      type: object

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    BadRequest:
      description: Request invalid or malformed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    ServerError:
      description: API error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
      description: >
        Prefix the value with `\"apikey\"` to indicate the custom authorization type.
        The key can be created by a company admin by going to https://app.mural.co/
